### ISSUE TITLE
Set from code

### ISSUE THREAD

**Issue by Hehahdhsafds** [XamlAnimatedGif/WpfAnimatedGif#100]
So I want to use it on a border
but i need it to work from code
i found a way to use it on a border using visual brushes but i can't use it in code

**Comment by thomaslevesque** [comment]
Hi @Hehahdhsafds,
Not sure what you're asking exactly... What do you mean "can't use it from code"? Anything you can do in XAML can also be done in code...
Anyway, if you want to use an animated GIF as a brush, I suggest you use [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif) instead, which has [explicit support for this scenario](https://github.com/XamlAnimatedGif/XamlAnimatedGif/blob/master/XamlAnimatedGif/BrushAnimator.cs).

**Comment by Hehahdhsafds** [comment]
thanks
