### ISSUE TITLE
The name "ImageBehavior" does not exist in the namespace "http://wpfanimatedgif.codeplex.com".	

### ISSUE THREAD

**Issue by apolloneo** [XamlAnimatedGif/WpfAnimatedGif#19]
I added dll file to my project's reference and added xmlns:gif="http://wpfanimatedgif.codeplex.com" to my xaml name space.

but I got error as title shown in my error list. It doesn't prevent me to build my project, but only cannot see the design GUI from VS.

any idea about it? I'm using VS2013 under Windows 7. thanks!

**Comment by thomaslevesque** [comment]
It looks like the issue described here: http://wpfanimatedgif.codeplex.com/discussions/564916
Check if the given solution works for you.

It shouldn't happen if you install the library via Nuget
________________________________
De : apolloneo<mailto:notifications@github.com>
Envoyé : ‎25/‎09/‎2015 23:31
À : XamlAnimatedGif/WpfAnimatedGif<mailto:WpfAnimatedGif@noreply.github.com>
Objet : [WpfAnimatedGif] The name "ImageBehavior" does not exist in the namespace "http://wpfanimatedgif.codeplex.com".  (#19)

I added dll file to my project's reference and added xmlns:gif="http://wpfanimatedgif.codeplex.com" to my xaml name space.

but I got error as title shown in my error list. It doesn't prevent me to build my project, but only cannot see the design GUI from VS.

any idea about it? I'm using VS2013 under Windows 7. thanks!

---
Reply to this email directly or view it on GitHub:
https://github.com/XamlAnimatedGif/WpfAnimatedGif/issues/19

**Comment by apolloneo** [comment]
Hi,

Yes, it is the issue and the solution works for me, too. Thanks!

**Comment by joshiji** [comment]
Since that page is deleted so posting a hint here(based on archive.org view):
If you downloaded the DLL File directly, then you need to right click on DLL and unblock it as windows sometimes blocks files downloaded from internet. Best way to use is to install using Nuget package manager.
