### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Kryptos-FR** [XamlAnimatedGif/WpfAnimatedGif#21]
I'm interested to use your library in a project.

However it is not clear whether this project is or is not copyleft? Without a license file, the default of any GitHub project is to be under default copyright laws (see https://help.github.com/articles/open-source-licensing/). Is it the case here?

**Comment by thomaslevesque** [comment]
Hi,

Sorry, I forgot to add a license... You can consider the project to be under the Apache 2.0 license. I'll add it as soon as I can.

**Comment by thomaslevesque** [comment]
Done: https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/master/LICENSE.txt
