### ISSUE TITLE
New Project Proposal

### ISSUE THREAD

**Issue by NickeManarin** [XamlAnimatedGif/WpfAnimatedGif#23]
Hi, do you remember when I asked about a possible project for creating gifs (encoding), a few months ago?

Are you interested? There is no reliable source for gif creating in .Net, the only ones are **Bumpkit** and **Ngif** (one uses bad quality and other is full of bugs and slow).

I can actively help you if you need, but I dont have the knowledge to do it alone.

The main idea is this:

- Should accept images (bmp, png, jpg), BitmapSources or Streams as input.
- Custom frame sizes, using (x, y, width, heigh), this is allowed by the gif specification.
- Variable frame rate.
- Transparency (Replaces the unchanged pixel with a dummy color).
- Progression report, in %. 
- Number of colors, from 255 to 2 colors (+ 1 transparent/dummy color), very important!.

PS: I also have a method that analizes the list of frames and cuts + paints the unchanged pixels to reduce the file size.

_Not sure if this is the right place to ask this, btw._

**Comment by thomaslevesque** [comment]
To be honest, I'm not interested in working on this, mostly because it's not something I need, and I don't have the time to work on something I don't need :wink:

If you want to do it anyway, feel free to reuse some code from WpfAnimatedGif or XamlAnimatedGif.
