### ISSUE TITLE
Setting URI kind to relative disables animation of gifs

### ISSUE THREAD

**Issue by Zircon99** [XamlAnimatedGif/WpfAnimatedGif#25]
hi Thomas, 

I have tried several ways to get the animation working using relative URI, but unable to do so. I implement a delegate method registered to Animationloaded, sender receiver is then null and unable to Play(). 

Setting autostart = true also does not work when relative URI is used. When I switch to absolute URI everything works - the delegate method sender != null so play() works fine and autostart also works. 

Can you kindly assist?

**Comment by thomaslevesque** [comment]
Hi,

I don't really understand what you're trying to do and what you've done so far... Could you show some code?

**Comment by Bearsuny** [comment]
I think what he said is:
When you use relative URI to get the gif animation, the animation only act like a static image. The animation can't play. Like this:
`BitmapImage _faceMaskGif = new BitmapImage();
            _faceMaskGif.BeginInit();
            _faceMaskGif.UriSource = new Uri("/Assets/14.gif", UriKind.Relative);
            _faceMaskGif.EndInit();`
But when you use absolute URI to get the gif animation, the animation can play well.
`BitmapImage _faceMaskGif = new BitmapImage();
            _faceMaskGif.BeginInit();
            _faceMaskGif.UriSource = new Uri("pack://application:,,,/Assets/14.gif");
            _faceMaskGif.EndInit();`
Actually, I aslo met this issue, and I didn't find the solution to solve. I still use absolute URI. :(

**Comment by Zircon99** [comment]
hi there

So sorry, I did not get back - I have been travelling.

Indeed, correct. I also use absolute URI now, use a work around to resolve
the relative URI and all is well.

Thank you!

Rolf

**Comment by thomaslevesque** [comment]
Yes, you have to specify an absolute URI if you set the image from code-behind.

Relative URIs are supported in XAML, because the XAML stack has a mechanism to resolve the absolute URI (see the [IUriContext interface](https://msdn.microsoft.com/en-us/library/system.windows.markup.iuricontext.aspx)).

**Comment by Zircon99** [comment]
Great thank you, but all sorted. The library has been useful, thank you for
assisting.

Rolf
