### ISSUE TITLE
Assembly is not Signed

### ISSUE THREAD

**Issue by JohanKustner** [XamlAnimatedGif/WpfAnimatedGif#26]
Would it be possible to get the assembly signed?

**Comment by thomaslevesque** [comment]
Hi @JohanKustner,

When you say "signed", I assume you mean strong-named? Sorry, but strong-signing for OSS projects is a major PITA, and I'm not willing to take that burden...

If you really need strong-naming, I suggest you use [Assembly Strong-Naming Toolkit](https://www.nuget.org/packages/Nivot.StrongNaming/), which can sign unsigned assemblies in NuGet packages.
