### ISSUE TITLE
Can open the large size gif

### ISSUE THREAD

**Issue by lindexi** [XamlAnimatedGif/WpfAnimatedGif#33]
I have a gif that has a 4520 height and 4520 widths and the app can't open it.

I upload the image to http://7xqpl8.com1.z0.glb.clouddn.com/%E4%BC%9A%E7%82%B8gif.GIF.

![](http://7xqpl8.com1.z0.glb.clouddn.com/34fdad35-5dfe-a75b-2b4b-8c5e313038e2%2F2017913113238.jpg)

But when I open Uri that I can show the image but when I open the file that I can't show it.

**Comment by thomaslevesque** [comment]
I'm not sure what you're trying to do here... This isn't an animated GIF, you don't need WpfAnimatedGif (or any other library) to display it. WpfAnimatedGif detects that the image has a single frame, and just sets it as the `Source` of the `Image` control. It doesn't do anything else.

However the image is *very* large, so it's possible that most of it is outside the screen (or at least outside the view). Have you tried setting `Stretch="Uniform"` on the `Image` control?

**Comment by thomaslevesque** [comment]
I'm closing the issue, as it doesn't appear to be an issue with the library itself.

**Comment by lindexi** [comment]
I will try to get the frame in gif and I will detect it only have an image.
