### ISSUE TITLE
Gif are not animated when the BitmapImage is already downloaded when settting animation source

### ISSUE THREAD

**Issue by valhentai** [XamlAnimatedGif/WpfAnimatedGif#34]

**Comment by thomaslevesque** [comment]
Hi @valhentai,

Could you give more details on how to reproduce the issue?

**Comment by valhentai** [comment]
I was wrong, it is not when image is already loaded. It happen when the BitmapImage is already downloaded.
if I do 
```
ImageModule.BitmapImage.DownloadCompleted += (e, a) =>
 {
       ImageBehavior.SetAnimatedSource(image, ImageModule.BitmapImage);
  };
```
There will be no animation. When I set the AnimatedSource when BitmapImage.IsDownloading is true, the animation will work.

**Comment by valhentai** [comment]
I don't have this problem with **XamlAnimatedGif** but the animation is too slow with this library.

**Comment by valhentai** [comment]
I got an AnimationLoaded event but `GetAnimationController` return null. So I must reach this part of the code https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/5e30f4e514170534b40ae8a23ec48854c5e732e9/WpfAnimatedGif/ImageBehavior.cs#L408-L412
My BitmapImage use a stream source and not a Uri so 
https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/5e30f4e514170534b40ae8a23ec48854c5e732e9/WpfAnimatedGif/ImageBehavior.cs#L369
must be false.

**Comment by thomaslevesque** [comment]
OK, so there seems to be multiple problems... Not sure where it's coming from. If you could provide a short but complete example that reproduces the issue, it would be very helpful.

**Comment by valhentai** [comment]
I did some debbuging and in the end the problem didn't came from your library. My BitmapSource reference was changed so when I setted set animation source at different time I ended up setting a different source and one was corrupted.

**Comment by thomaslevesque** [comment]
I'm glad you were able to solve your problem. Thanks for letting me know!
