### ISSUE TITLE
Pause/Resume on visibility changed

### ISSUE THREAD

**Issue by mivor** [XamlAnimatedGif/WpfAnimatedGif#37]
Hi,

As far as I can tell the animation keeps running in the background even when the image is not visible.
Would it be possible to pause and resume the animation when the image visibility changes?

I would be willing to create a PR for this, if you agree with the change.

**Comment by thomaslevesque** [comment]
Hi @mivor,

Thanks for the suggestion, it's a great idea!

> I would be willing to create a PR for this, if you agree with the change.

Please go ahead 👍

**Comment by thomaslevesque** [comment]
Hi @mivor,

Are you still interested in working on this?

**Comment by thomaslevesque** [comment]
Closed in #58

**Comment by thomaslevesque** [comment]
This change has been released in v1.4.18, which will be available on Nuget as soon as validation and indexing are complete. Thanks @khersonIT!
