### ISSUE TITLE
What happen if i set the 'AnimatedSource' with static image like PNG or JPG?

### ISSUE THREAD

**Issue by kuchienkz** [XamlAnimatedGif/WpfAnimatedGif#38]
I have an Image control which at certain condition it shows an animated gif, else static image. Im planning to use Trigger for that.

**Comment by thomaslevesque** [comment]
@kuchienkz you don't need a trigger. If `AnimatedSource` is a static image, it will be displayed normally as if you had set `Source` instead.

**Comment by kuchienkz** [comment]
Well done!
