### ISSUE TITLE
Flickering when not at native size

### ISSUE THREAD

**Issue by Unit2Ed** [XamlAnimatedGif/WpfAnimatedGif#42]
I've got a ~3 second gif in an Image control. When the control is allowed to size automatically (ie I haven't specified width or height), it displays fine at the gif's original dimensions. If I shrink the control by setting width/height, the gif flickers between rendering at it's original size (but clipped by the width/height set, meaning you can only see a bit of it), and rendering scaled to fit the control. The flicker pattern doesn't seem to be consistent (it changes at different times in the gif each loop), though it does spend more time at original size than scaled.

Have you seen this before?

**Comment by thomaslevesque** [comment]
Hi @Unit2Ed,

No, I haven't seen this before. I just tried, and I can't reproduce it. Could you share some code?

**Comment by Unit2Ed** [comment]
From an empty WPF (.Net 4.6.1 / VS 2017) project, I Nuget'd WpfAnimatedGif, and then added this xaml inside the grid:

<Image x:Name="gif" gif:ImageBehavior.AnimatedSource="C:\\small-gif-16.gif" Width="100" Height="100"/>

Any gif I try seems to have this issue (I used http://gifimage.net/wp-content/uploads/2017/08/small-gif-16.gif in the above example).

**Comment by Unit2Ed** [comment]
Nevermind - I've found the problem - I have Intel GPA running in the background, and somehow that interferes with the Image control; turning it off sorts the problem.

**Comment by thomaslevesque** [comment]
👍 
Glad you found the solution!
