### ISSUE TITLE
Strong named?

### ISSUE THREAD

**Issue by ErikEJ** [XamlAnimatedGif/WpfAnimatedGif#44]
Trying to use this in a VS extension, but that requires the dll to be strong named - is that available?

**Comment by thomaslevesque** [comment]
Hi @ErikEJ,

Sorry, I don't have a strong named version. However there are ways to strong-name assemblies in Nuget packages:
- https://blog.maartenballiauw.be/post/2014/09/10/automatically-strong-name-signing-nuget-packages.html
- [Assembly Strong-Naming Toolkit](https://www.nuget.org/packages/Nivot.StrongNaming/)

**Comment by ErikEJ** [comment]
Thanks, I will strong name the dll
