### ISSUE TITLE
Filestream error

### ISSUE THREAD

**Issue by fred37000** [XamlAnimatedGif/WpfAnimatedGif#46]
Hi,
Thanks for sharing your wpf gif library.

I've a problem. When I writing gif file in second time with IO.Filestream , this code below give me an Error because the gif file is launched with another program. 

Code : 
gifImage.BeginInit();
gifImage.UriSource = new Uri(path);
gifImage.EndInit();
ImageBehavior.SetAnimatedSource(photosGif_finale, gifImage);

What methods should i use to stop this reference for pushing another new gif?
I hope is clear, sorry for my bad english.

Thanks.

**Comment by thomaslevesque** [comment]
Hi @fred37000,

You should set `gifImage.CacheOption` to `BitmapCacheOption.OnLoad` during initialization. This will cause the image to be completely loaded during initialization, so that the file can be released.

**Comment by fred37000** [comment]
Exactly, thanks for quickly answer !

**Comment by thomaslevesque** [comment]
You're welcome!
