### ISSUE TITLE
how to pause the animation in MVVM-VM In WPF?

### ISSUE THREAD

**Issue by JinDai-Han** [XamlAnimatedGif/WpfAnimatedGif#47]
Question1:how to get the controller or any DependencyProperty to make the binding to the View 's ?
Question2:
![7-3](https://user-images.githubusercontent.com/37918710/42213979-d20b64a4-7eec-11e8-8f02-ae49ed29fd05.png)

**Comment by thomaslevesque** [comment]
> Question1:how to get the controller or any DependencyProperty to make the binding to the View 's ?

Sorry, I don't understand what you mean... Could you elaborate?

> Question2:

In some cases the animation cannot be loaded synchronously. You should subscribe to the `AnimationLoaded` attached event to detect when it is loaded, and then get the controller.

**Comment by JinDai-Han** [comment]
you know.I just want to pause/play the gif in ViewModel(MVVM).Is there any way to do this in xaml code or any property I can set to pause/play the GIF in my WPF project? because theViewModel doesn't know the View existed.so get the controller of the GIF isn't easy.I don't want to use (controller.Play();controller.Pause()).Or can you offer some good solutions?

**Comment by thomaslevesque** [comment]
@JinDai-Han sorry, there's no way to directly control the animation via bindings. `AnimationController` is an attached property, so you could bind to it, but the controller has no settable properties, it's only manipulated with methods.

You could, however, create a bindable "bridge" that could manipulate the controller. For instance, it could have a `IsRunning` property that would start or stop the controller, and you could bind this property to your ViewModel

**Comment by JinDai-Han** [comment]
@thomaslevesque  Thank you for your prompt reply. I got the controller by subscribing to the AnimationLoaded event .

**Comment by thomaslevesque** [comment]
@JinDai-Han you're welcome! Glad to have been of help.
