### ISSUE TITLE
Exception from F# WPF 

### ISSUE THREAD

**Issue by giuliohome** [XamlAnimatedGif/WpfAnimatedGif#53]
I'm getting this exception

```
Cannot set unknown member '{http://wpfanimatedgif.codeplex.com}ImageBehavior.AnimatedSource'."}
	System.Exception {System.Xaml.XamlObjectWriterException}
```

I'm in F# App.fs at startup

```
[<STAThread>]
[<EntryPoint>]
let main argv =
    try
        if SynchronizationContext.Current = null then
            DispatcherSynchronizationContext(Dispatcher.CurrentDispatcher)
            |> SynchronizationContext.SetSynchronizationContext
```

and the xaml is the standard
```
xmlns:gif="http://wpfanimatedgif.codeplex.com"
...
<Image gif:ImageBehavior.AnimatedSource="gif\spinner1.gif"  ...
```

**Comment by giuliohome** [comment]
Solved by using a C# User Control (then imported into the F# WPF project)

**Comment by giuliohome** [comment]
I can close the issue with my simple workaround. I think the root cause is due to some event handling inside this project that is not compatible with the more limited xaml functionalities in FsXaml for F#. 
If anyone is willing to get a deeper insight and to reenginer this package for direct use in such a F# project, then welcome and feel free to reopen...

**Comment by thomaslevesque** [comment]
Hi @giuliohome,

Thanks for reporting this. I have no idea what in the library could be causing this. I suspect it's related to how XAML is handled in F# project, but I have no experience with this. As another workaround, you could set `AnimatedSource` in code behind (`ImageBehavior.SetAnimatedSource(imageControl, image)`)

**Comment by giuliohome** [comment]
Thank you very much for your suggestion. I will try soon and I think it will work. It is exactly what I also wanted to try. I'll let you know.

**Comment by thomaslevesque** [comment]
It doesn't seem to be the same problem. A `COMException` usually indicates a problem at a pretty low level, and honestly, it's so deep into WPF code that I have no idea what could be causing it...

Anyway, I'm glad you were able to use XamlAnimatedGif instead
