### ISSUE TITLE
How to use it for SplashScreen?

### ISSUE THREAD

**Issue by ranjan-ranjan** [XamlAnimatedGif/WpfAnimatedGif#56]
How to use it for SplashScreen?

**Comment by thomaslevesque** [comment]
You mean the `SplashScreen` class? There's no way at all to customize it, so it's not possible. You'll have to create your own custom splashscreen window.

**Comment by ranjan-ranjan** [comment]
Ok
So, there's no way to use gif using WpfAnimatedGif?

**Comment by ranjan-ranjan** [comment]
Ok. thanks a lot
