### ISSUE TITLE
Gif animation is slowed down.

### ISSUE THREAD

**Issue by DoomBroMax** [XamlAnimatedGif/WpfAnimatedGif#59]
I didn't notice it at first, cause it's not much. But when I play a gif animation with this library in WPF, the animation is slower than when I'd just play it by opening it directly. It also runs at the normal speed with the WpfAnimatedGif library. It's really not much, but it was noticable when playing a sound effect that would usually be in sync with the animation. Is there a way to adjust the speed of the gif?

**Comment by thomaslevesque** [comment]
> when I play a gif animation with this library in WPF, the animation is slower

> It also runs at the normal speed with the WpfAnimatedGif library

I'm not sure I understand what you mean... this library *is* WpfAnimatedGif 😉 

> Is there a way to adjust the speed of the gif?

No, there isn't. The timing is controlled by a WPF `ObjectAnimationUsingKeyFrames`; I would have expected the timing to be accurate, but if it's not, there isn't much I can do about it, as the problem would be in WPF itself. *Unless* I have a bug where I create the keyframes, but the [code](https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/e07b77b7351d5ab03b0cd979cc64d002e8a8caeb/WpfAnimatedGif/ImageBehavior.cs#L438-L470) is quite straightforward...

I could provide a way to control the animation's [SpeedRatio](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.animation.timeline.speedratio?view=netframework-4.7.2#System_Windows_Media_Animation_Timeline_SpeedRatio), which would let you control the speed. Would that help?

**Comment by DoomBroMax** [comment]
Well me being an idiot posted this issue on the wrong project. I meant to post it on the XamlAnimatedGif repository. And I don't know if it's WPF. Since in the one library it's normal speed, in the other it's not. But being able to control the speed would be a big help, yes. Not just in fixing my problem but also would give my program more options.

**Comment by thomaslevesque** [comment]
Ah, I see. XamlAnimatedGif works differently. It does the GIF decoding itself and renders frames on the fly. It uses less RAM than WpfAnimatedGif (which prepares all the frames in advance), but performance isn't very good... When it takes too long to render a frame, the animation is slowed.

**Comment by DoomBroMax** [comment]
Ah I see. Hmm, this might be a problem. I switched from the old library to the new one, because the animations were loading much faster, probably because it's frame by frame now, not the whole gif at once.
This...is a tricky problem now. Guess I have to find another way. Thanks for your answer.

**Comment by thomaslevesque** [comment]
I have plans to improve performance, but it might be a while before I find the time to work on it...
