### ISSUE TITLE
File getting locked

### ISSUE THREAD

**Issue by shrutisingh1993** [XamlAnimatedGif/WpfAnimatedGif#60]
I am using XamlAnimatedGif to play different GIFs, which I am creating through code. I am creating a unique file every time a GIF is to be played and hence the GIF player will play one GIF only once. So, in the process, I created say 10 GIFs, and previewed them as well. And every GIF successfully raised AnimationCompleted event. Post this event is raised, I am trying to delete the file from my hard disk. But there is a lock on the file. 
My XAML looks like below, where the binded path property keeps on changing on everytime I create and preview a new GIF:

```xaml
<Image gif:ImageBehavior.AnimatedSource="{Binding GifImagePath}"
       gif:ImageBehavior.AutoStart="true" 
       gif:ImageBehavior.RepeatBehavior="{Binding RepeatBehavior}"
       gif:ImageBehavior.AnimationCompleted="AnimationCompleted">
```

**Comment by thomaslevesque** [comment]
Hi @shrutisingh1993,

> I am using XamlAnimatedGif

This repo is for WpfAnimatedGif, an older library. Did you mean to open the issue in https://github.com/XamlAnimatedGif/XamlAnimatedGif?

The file is locked while it's being played. You could just clear the animation source from the image before attempting to delete the file.
Alternatively, since you're generating temporary GIFs, you could skip writing them to files entirely and work only in memory, using a `MemoryStream`.

**Comment by shrutisingh1993** [comment]
I require GIF in a file since I am maintaining project state. Also I see that there is a dependency on BitmapSource for to play the GIF in [ImageBehavior.cs](https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/master/WpfAnimatedGif/ImageBehavior.cs).

```
BitmapSource source = GetAnimatedSource(imageControl) as BitmapSource;
//When GIF is available to play, we do
imageControl.Source = source;
```

And `BitmapSource` does not provide `CacheOption` property. Do we have any other workaround here?

**Comment by thomaslevesque** [comment]
> Also I see that there is a dependency on BitmapSource for to play the GIF in [ImageBehavior.cs](https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/master/WpfAnimatedGif/ImageBehavior.cs).
> 
> ```
> BitmapSource source = GetAnimatedSource(imageControl) as BitmapSource;
> //When GIF is available to play, we do
> imageControl.Source = source;
> ```

That's not how the library is used... You should never manually set `imageControl.Source` (if you do, it won't be animated).

> And `BitmapSource` does not provide `CacheOption` property.

No, but `BitmapImage` inherits from `BitmapSource`, and has that property. You can do this:

```csharp
var bitmap = new BitmapImage();
bitmap.BeginInit();
bitmap.CacheOption = BitmapCacheOption.OnLoad;
bitmap.UriSource = new Uri("the/path/to/the/file.gif");
bitmap.EndInit();
ImageBehavior.SetAnimatedSource(imageControl, bitmap);
```

This won't lock the file

**Comment by shrutisingh1993** [comment]
I am not setting imageControl.Source. I have now binded AnimatedSource to a BitmapImage, which loads in memory and it worked. And when the animation stops, I set the binded property to null. That releases my GIF file on hard disk.
Thanks for your help.
