### ISSUE TITLE
Support for .NET Core 3.0

### ISSUE THREAD

**Issue by AuldinSolutions** [XamlAnimatedGif/WpfAnimatedGif#63]
Any plans to update to support .NET Core 3.0 which now supports WPF?

**Comment by thomaslevesque** [comment]
Hi @AuldinSolutions,

I haven't really thought about it, but yes, it's definitely something that I'd like to do. No promise for a release date, though...

**Comment by aemarco** [comment]
according to the portabilityanalyzer, the library itself is 100%  supported by .net core 3 with PlatformExtensions, wpf is windows only anyways^^

thanks for the great stuff, loving it 👍

**Comment by thomaslevesque** [comment]
> hmmm... since it would be .net core directly, it would need to be available for .net framework still.
> no idea how to support .net framework and core at the same time.

Not a problem now with SDK-style projects

**Comment by mcdis** [comment]
Really needs...

**Comment by KiKoS0** [comment]
Hi everyone, i needed this library for a .net core 3.1 project so i fastly modified the project file to support .net core, i'd be happy to change what needs to be changed to meet @thomaslevesque build structure that you want and pr it. Here is the my working .net core [branch](https://github.com/KiKoS0/WpfAnimatedGif/tree/net-core-branch).

**Comment by thomaslevesque** [comment]
@KiKoS0 thanks, that looks great! Could you please submit a PR?

**Comment by thomaslevesque** [comment]
Support for .NET Core 3.0 has been introduced in [2.0.0-beta.1](https://github.com/XamlAnimatedGif/WpfAnimatedGif/releases/tag/2.0.0-beta.1)

Thanks @KiKoS0!
