### ISSUE TITLE
Copyright Notice

### ISSUE THREAD

**Issue by sbernardjr** [XamlAnimatedGif/WpfAnimatedGif#64]
I am writing an application that makes use of WpfAnimatedGif and I am trying to ensure I comply with its license. The Apache 2.0 license you've selected requires that I preserve your copyright notice, but I don't see any copyright notice in your project.

Near the bottom of https://github.com/XamlAnimatedGif/WpfAnimatedGif/blob/master/LICENSE.txt there is a section that reads:

    Copyright {yyyy} {name of copyright owner}

Is it possible that you could fill out this copyright information in your license so that I can include it in my application package?

**Comment by thomaslevesque** [comment]
@sbernardjr done!
I never realized I had to modify it... Thanks for telling me!
