### ISSUE TITLE
2nd gif does not play

### ISSUE THREAD

**Issue by luskos1** [XamlAnimatedGif/WpfAnimatedGif#65]
Got a source image with a gif, then modify it and try to load modified version into preview image control, only original image control play gif animations. Both are set the same just the preview leads to new file. Does not play.

**Comment by thomaslevesque** [comment]
Hi @luskos1,

Sorry, I don't really understand what you're doing... Could you show some code?

**Comment by luskos1** [comment]
I have 2 image controls, one for displaying the original gif i load the
other to display modified version, i take original and diasemble it to
frames, change color schemes and reasemble it to another gif. Code is
pretty straight forward  what i use for the first one that i try for the
second preview, but it soes not play modified gif.

**Comment by thomaslevesque** [comment]
Could you please show the code to set the GIF in the second image?
Or even better, provide a minimal repro?

**Comment by luskos1** [comment]
The code is straight forward as the example. I am porting the project to
wpf and just to be sure of it all this time just noticed that it does not
assemble all the frames back into produced gifs. It repeats first frame
twice that's why it seemed as static image. So it's false positive on my
side. Sorry to bother you and compliments on your plugin.

>

**Comment by thomaslevesque** [comment]
Thanks for the feedback @luskos1, glad you sorted it out!
