### ISSUE TITLE
wpf vs xaml version

### ISSUE THREAD

**Issue by jenokizm** [XamlAnimatedGif/WpfAnimatedGif#70]
hi! i have wpf net 4.6 project. Which library should I use? **XamlAnimatedGif** or **WpfAnimatedGif**? What is the difference and is there any need for wpf if xaml everything supports?

**Comment by thomaslevesque** [comment]
Hi @jenokizm,

You can use either one of those libraries. XamlAnimatedGif is a rewrite of WpfAnimatedGif which tries to solve some problems of WpfAnimatedGif, but unfortunately introduces others...

**WpfAnimatedGif**
- works only on WPF
- has very good rendering performance
- uses a lot of memory, especially for large GIFs with many frames

**XamlAnimatedGif**
- works on multiple XAML platforms (WPF, UWP, Windows Phone, Silverlight...)
- uses much less memory
- has slow rendering performance for large GIFs (but isn't affected by the number of frames)

Just choose what works best for you ;)

**Comment by jenokizm** [comment]
@thomaslevesque, thanks for the comprehensive answer. I also want to say you're doing a great job!

**Comment by thomaslevesque** [comment]
You're welcome!
