### ISSUE TITLE
feature request: grayscale mode

### ISSUE THREAD

**Issue by alexeygritsenko** [XamlAnimatedGif/WpfAnimatedGif#72]
hi, it would be great if you added the ability to view animations in black and white. This is useful in many usage scenarios, such as unobtrusive demonstrations of some kind of animation.

**Comment by thomaslevesque** [comment]
You can do that by applying a effect on the image control. You can find an example here: http://neverindoubtnet.blogspot.com/2009/05/pixelshader-that-means-business.html

**Comment by alexeygritsenko** [comment]
OK. https://www.nuget.org/packages/GrayscaleEffect/ work it.
