### ISSUE TITLE
System.Windows.Markup.XamlParseException during runtime

### ISSUE THREAD

**Issue by ypeng-ming** [XamlAnimatedGif/WpfAnimatedGif#73]
Hello, I'm using VS2019, WPF in .Netcore 3.0
GIF works well in XAML, but an error is thrown during runtime, I followed an example which I downloaded from Monsieur Levesque. Did I do something wrong or miss something? S'il vous plait. Merci par avance.
![image](https://user-images.githubusercontent.com/52032205/71876259-4eb07f80-3161-11ea-8da8-fdf362ec0d9b.png)
XAML code is very basic, so I put only the first few lines:
[Window x:Class="Page_IDCard_4.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Page_IDCard_4"
        xmlns:gif="http://wpfanimatedgif.codeplex.com"
        gif:ImageBehavior.AnimateInDesignMode="True"
        mc:Ignorable="d"
        Height="1080" Width="1920" WindowStyle ="None"  WindowStartupLocation="CenterScreen" ResizeMode="NoResize" AllowsTransparency="True">](url)

Par contre, je parle aussi en Français, si vous voulez, Merci, Bonne Journee.

**Comment by thomaslevesque** [comment]
Hi @ypeng-ming,

> Par contre, je parle aussi en Français, si vous voulez,

Nice! But I think it's better to speak English here, so that others can benefit from the conversation.

When you say

> GIF works well in XAML

do you mean you see the GIF animation in the designer?

Could you show the code where you set `ImageBehavior.AnimatedSource` on the image? And the complete error message (translated please... I don't speak Chinese :wink:)

**Comment by ypeng-ming** [comment]
Hi, Thomas, Thanks for your responds,

Yes, I see GIF animation in the designer.

**Image setting is below:**
 <Image Grid.Column="4" Grid.Row="5" gif:ImageBehavior.AnimatedSource="Assets/欢迎页-身份证识别-动图.gif" gif:ImageBehavior.RepeatBehavior="Forever" 
             gif:ImageBehavior.AutoStart="True" ></Image> 


**Error message:**

System.Windows.Markup.XamlParseException: '“在“System.Windows.Baml2006.TypeConverterMarkupExtension” have an exception when provide value.”，line“35”，colonne“30”.'

**Inner Exception:**
IOException: couldn't find resource“assets/%e6%ac%a2%e8%bf%8e%e9%a1%b5-%e8%ba%ab%e4%bb%bd%e8%af%81%e8%af%86%e5%88%ab-%e5%8a%a8%e5%9b%be.gif”.

**This exception was originally thrown at this call stack:**
	MS.Internal.AppModel.ResourcePart.GetStreamCore(System.IO.FileMode, System.IO.FileAccess)
	System.IO.Packaging.PackagePart.GetStream(System.IO.FileMode, System.IO.FileAccess)
	MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(System.IO.Packaging.PackagePart, System.IO.FileMode, System.IO.FileAccess)
	System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
	System.IO.Packaging.PackWebResponse.GetResponseStream()
	System.IO.Packaging.PackWebResponse.ContentType.get()
	System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCacheOption, out System.Guid, out bool, out System.IO.Stream, out System.IO.UnmanagedMemoryStream, out Microsoft.Win32.SafeHandles.SafeFileHandle)
	System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy, bool)
	System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(System.Uri, System.Uri, System.IO.Stream, System.Windows.Media.Imaging.BitmapCreateOptions, System.Windows.Media.Imaging.BitmapCacheOption, System.Net.Cache.RequestCachePolicy)
	System.Windows.Media.ImageSourceConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext, System.Globalization.CultureInfo, object)
    ...
    [Call Stack Truncated]

when it says "couldn't find resource" in the inner exception, it doesn't make any sense, because, GIF animate correctly in designer.

**Comment by ypeng-ming** [comment]
**Image setting is below:**
<Image Grid.Column="4" Grid.Row="5" gif:ImageBehavior.AnimatedSource="Assets/欢迎页-身份证识别-动图.gif" gif:ImageBehavior.RepeatBehavior="Forever" 
             gif:ImageBehavior.AutoStart="True" ></Image>

**Comment by ypeng-ming** [comment]
**Image setting is below:**
[<Image Grid.Column="4" Grid.Row="5" gif:ImageBehavior.AnimatedSource="Assets/欢迎页-身份证识别-动图.gif" gif:ImageBehavior.RepeatBehavior="Forever" 
             gif:ImageBehavior.AutoStart="True" ></Image>](url)

**Comment by ypeng-ming** [comment]
<Image Grid.Column="4" Grid.Row="5" gif:ImageBehavior.AnimatedSource="Assets/欢迎页-身份证识别-动图.gif" gif:ImageBehavior.RepeatBehavior="Forever" 
             gif:ImageBehavior.AutoStart="True" ></Image>

**Comment by thomaslevesque** [comment]
I suspect the problem has nothing to do with WpfAnimatedGif, but with WPF itself... If you change the code like this:

```xaml
<Image Grid.Column="4" Grid.Row="5" Source="Assets/欢迎页-身份证识别-动图.gif"></Image> 
```

You will see the same problem (image shows up in designer, but not at runtime)

I think you need to specify the absolute path of the resource, something like `"/Assets/欢迎页-身份证识别-动图.gif"` or maybe `"pack://application:,,,/Assets/欢迎页-身份证识别-动图.gif"`

**Comment by ypeng-ming** [comment]
Hello, Thomas,
Thanks for your answer, you are right, the problem is nothing to do with WpfAnimatedGif. I changed the Image path to absolute path of resource, it works perfectly!! Thank you so much for your help.

**Comment by ypeng-ming** [comment]
Hello, Thomas,
Thanks for your answer, you are right, the problem is nothing to do with WpfAnimatedGif. I changed the Image path to absolute path of resource, it works perfectly!! Thank you so much for your help.
