### ISSUE TITLE
The gif always resumes on visibility changed

### ISSUE THREAD

**Issue by Duckheady** [XamlAnimatedGif/WpfAnimatedGif#74]
Good day,

I have an issue related to, but opposite of issue #37. The behavior I am expecting is that a paused gif stay paused if AnimationController's Pause() method was the last method called on the controller. This behavior works properly when swapping between user controls, swapping between pages, etc. However, it fails when I directly tell the user control the image is a part of to become hidden and then to become visible again(directly to the control is untested).

After some work, I registered an event to execute when the visibility changed event is raised; however, it must be after animation controller has loaded for me to register it, as I need my event to execute after your animation controller executes it's event (presumably) to resume the gif's animation.

While I am mostly certain the bug is not related to this, I would like to note that I am utilizing a control derived from Image.

Feel free to close this issue, as I have found the workaround detailed above, but I just wanted to file a bug to assist your development of a great tool you have here. Additionally, while unrelated, I have found a way to reliably reproduce issue #52, but it may be related to .net classes rather than your library. If, in Visual Studio, the resource file's property "Build Action" is set to None as opposed to "Resource" it will reliably reject the image. Mysteriously, this issue will persist with even correctly configured files deployed through an installer, but the issue disappears over time. Very strange indeed.

(I apologize for the wordiness of this issue, this is my first time reporting an issue on an open source project, and I wanted to make clear what was happening.)

**Comment by thomaslevesque** [comment]
Hi @Duckheady,

Thanks for the report!

Let me reword the problem to make sure I understand correctly: you have a GIF animation in paused state, and when the control is hidden and shown again, the animation starts automatically, right?

**Comment by Duckheady** [comment]
Correct.

**Comment by thomaslevesque** [comment]
I'll look into it, but I won't be able to do it right away (in 2 or 3 weeks at best)

**Comment by thomaslevesque** [comment]
Hi @Duckheady,

I just published a new beta to NuGet ([2.0.0-beta.3](https://www.nuget.org/packages/WpfAnimatedGif/2.0.0-beta.3)) which should fix this. Could you check if it works for you?

**Comment by thomaslevesque** [comment]
@Duckheady, did that solve the problem for you? I'm waiting for your feedback before I publish the package as stable.
