### ISSUE TITLE
Examples fail....

### ISSUE THREAD

**Issue by GrantGussie** [XamlAnimatedGif/WpfAnimatedGif#77]
The XAML in the example file 
WpfAnimatedGif-master\WpfAnimatedGif.Demo\MainWindows 
fails to compile with
error MC3072: The property 'ImageBehavior.AnimateInDesignMode' does not exist in XML namespace 'http://wpfanimatedgif.codeplex.com'. 

The XAML in the example file 
WpfAnimatedGif-master\WpfAnimatedGif.Demo\TestRelativeUri.xaml
fails to compile with
The property 'ImageBehavior.RepeatBehavior' does not exist in XML namespace 'http://wpfanimatedgif.codeplex.com'

I tried replacing 
http://wpfanimatedgif.codeplex.com
with  
http://github.com/XAMLAnimatedGif/WpfAnimatedGif
and then
http://github.com/ThomasLevesque/WpfAnimatedGif
but the same problem occurs.

I downloaded the package with NuGet manager into Visual Studio 2019.
Sorry, but this code just does not work in this application.

**Comment by GrantGussie** [comment]
Note: I also read the note for the same problem
https://github.com/XamlAnimatedGif/WpfAnimatedGif/issues/19
but the link to the solution failed. It also said it should not happen if you use the NuGet package manager, which I tried, but no success.

**Comment by thomaslevesque** [comment]
Hi @GrantGussie,

Sorry you're having trouble. But I just checked, and the project compiles fine for me... There might be something wrong with your Visual Studio installation.

> I downloaded the package with NuGet manager into Visual Studio 2019.

I'm not sure I understand this remark. The demo project isn't in the NuGet package...

> I tried replacing
> http://wpfanimatedgif.codeplex.com
> with
> [http://github.com/XAMLAnimatedGif/WpfAnimatedGif](https://github.com/XAMLAnimatedGif/WpfAnimatedGif)
> and then
> [http://github.com/ThomasLevesque/WpfAnimatedGif](https://github.com/ThomasLevesque/WpfAnimatedGif)

No, the workspace is fine. It's the former URL of the project, before I migrated it to GitHub. I didn't change it when I migrated because it would have been a breaking change. But it's just an identifier for the namespace, the URL isn't actually accessed.

**Comment by GrantGussie** [comment]
Thank you Thomas for the prompt reply.
I realize my original post reads as being abrupt and curt, rather than concise, which I was aiming for. Sorry about that... it was a long day and I was getting tired.
 
To clarify my comment about downloading the package with NuGet manager... the note about the same problem I found (#19) mentioned that if you download the package with the NuGet manager you should not have this problem. So I tried to add the package to the demo manually that way. The add failed. And I still can't get the demo to compile. 

However, my own application did accept the Nuget package and now compiles and runs just fine... and frankly that's good enough for me.

However, I am including the output created when I tried to compile the demo (as downloaded from github) with Visual Studio 2019. 

As you can see, numerous errors occur, starting with "System.Exception: Failed to run Git". Is this is reference to a github extension (https://github.com/Haacked/VisualStudio)? 

1>------ Rebuild All started: Project: WpfAnimatedGif, Configuration: Debug Any CPU ------
1>
1>Unhandled Exception: System.Exception: Failed to run Git. Git may not be installed on the system. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>   at System.Diagnostics.Process.Start()
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 32
1>   --- End of inner exception stack trace ---
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 36
1>   at MinVer.Lib.Repository.TryCreateRepo(String workDir, Repository& repository, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Repository.cs:line 21
1>   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 36
1>   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, MajorMinor minMajorMinor, String buildMeta, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 9
1>   at MinVer.Program.<>c__DisplayClass1_0.<Main>b__0() in /home/runner/work/minver/minver/minver-cli/Program.cs:line 59
1>   at MinVer.Program.Main(String[] args) in /home/runner/work/minver/minver/minver-cli/Program.cs:line 31
1>
1>Unhandled Exception: System.Exception: Failed to run Git. Git may not be installed on the system. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>   at System.Diagnostics.Process.Start()
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 32
1>   --- End of inner exception stack trace ---
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 36
1>   at MinVer.Lib.Repository.TryCreateRepo(String workDir, Repository& repository, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Repository.cs:line 21
1>   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 36
1>   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, MajorMinor minMajorMinor, String buildMeta, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 9
1>   at MinVer.Program.<>c__DisplayClass1_0.<Main>b__0() in /home/runner/work/minver/minver/minver-cli/Program.cs:line 59
1>   at MinVer.Program.Main(String[] args) in /home/runner/work/minver/minver/minver-cli/Program.cs:line 31
1>
1>Unhandled Exception: System.Exception: Failed to run Git. Git may not be installed on the system. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
1>   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>   at System.Diagnostics.Process.Start()
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 32
1>   --- End of inner exception stack trace ---
1>   at MinVer.Lib.GitCommand.TryRun(String args, String workingDirectory, ILogger log, String& output) in /home/runner/work/minver/minver/MinVer.Lib/GitCommand.cs:line 36
1>   at MinVer.Lib.Repository.TryCreateRepo(String workDir, Repository& repository, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Repository.cs:line 21
1>   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 36
1>   at MinVer.Lib.Versioner.GetVersion(String workDir, String tagPrefix, MajorMinor minMajorMinor, String buildMeta, VersionPart autoIncrement, String defaultPreReleasePhase, ILogger log) in /home/runner/work/minver/minver/MinVer.Lib/Versioner.cs:line 9
1>   at MinVer.Program.<>c__DisplayClass1_0.<Main>b__0() in /home/runner/work/minver/minver/minver-cli/Program.cs:line 59
1>   at MinVer.Program.Main(String[] args) in /home/runner/work/minver/minver/minver-cli/Program.cs:line 31
1>C:\Users\Owner\.nuget\packages\minver\2.0.0\build\MinVer.targets(39,5): error MSB3073: The command "dotnet "C:\Users\Owner\.nuget\packages\minver\2.0.0\build\../minver/MinVer.dll" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --repo "D:\__WpfAnimatedControl\WpfAnimatedGif" --tag-prefix "" --verbosity "" --version-override """ exited with code -532462766.
1>Done building project "WpfAnimatedGif.csproj" -- FAILED.
1>C:\Users\Owner\.nuget\packages\minver\2.0.0\build\MinVer.targets(39,5): error MSB3073: The command "dotnet "C:\Users\Owner\.nuget\packages\minver\2.0.0\build\../minver/MinVer.dll" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --repo "D:\__WpfAnimatedControl\WpfAnimatedGif" --tag-prefix "" --verbosity "" --version-override """ exited with code -532462766.
1>C:\Users\Owner\.nuget\packages\minver\2.0.0\build\MinVer.targets(39,5): error MSB3073: The command "dotnet "C:\Users\Owner\.nuget\packages\minver\2.0.0\build\../minver/MinVer.dll" --auto-increment "" --build-metadata "" --default-pre-release-phase "" --minimum-major-minor "" --repo "D:\__WpfAnimatedControl\WpfAnimatedGif" --tag-prefix "" --verbosity "" --version-override """ exited with code -532462766.
1>Done building project "WpfAnimatedGif.csproj" -- FAILED.
2>------ Rebuild All started: Project: WpfAnimatedGif.Demo, Configuration: Debug Any CPU ------
2>D:\__WpfAnimatedControl\WpfAnimatedGif.Demo\MainWindow.xaml(5,9): error MC3072: The property 'ImageBehavior.AnimateInDesignMode' does not exist in XML namespace 'http://wpfanimatedgif.codeplex.com'. Line 5 Position 9.
2>D:\__WpfAnimatedControl\WpfAnimatedGif.Demo\TestRelativeUri.xaml(13,32): error MC3072: The property 'ImageBehavior.AnimatedSource' does not exist in XML namespace 'http://wpfanimatedgif.codeplex.com'. Line 13 Position 32.
2>Done building project "WpfAnimatedGif.Demo.csproj" -- FAILED.
========== Rebuild All: 0 succeeded, 2 failed, 0 skipped ==========

**Comment by thomaslevesque** [comment]
Ah, I see what's going on. MinVer is a package used by the library to compute a version number based on Git versioning. If MinVer can't find Git, it fails, so the library fails to build, and since the demo project depends on the library, it also fails...

How did you get the code? Did you clone the Git repo or just download the code? Is Git in your PATH?

**Comment by GrantGussie** [comment]
Hi... I just downloaded the code and unzipped the file. 

Then I opened the .sln file with VIsual Studio 2019.  The ,sln file updated to 2019 without problem. 

Then the only thing I did before trying to compile it is change the "Solution | Properties | Start Up Project" from "WpfAnimatedGif" to "WpfAnimatedGif.Demo". 

And GIT is not in my build path.
Cheers!
G

**Comment by thomaslevesque** [comment]
Glad we were able to sort that out. Yeah, you absolutely *need* Git to build the project... I never realized it could be a constraint, since I use Git for all my projects.
