### ISSUE TITLE
support .net Core 3.1

### ISSUE THREAD

**Issue by ourplan9000** [XamlAnimatedGif/WpfAnimatedGif#78]

**Comment by thomaslevesque** [comment]
Hi @ourplan9000,

.NET Core 3 is supported in the latest beta. I'm going to release a new stable version very soon, including .NET Core 3 support.

**Comment by thomaslevesque** [comment]
.NET Core 3 (including 3.1) support is included in [release 2.0.0](https://github.com/XamlAnimatedGif/WpfAnimatedGif/releases/tag/2.0.0).
