### ISSUE TITLE
Version is 0.0.0.0

### ISSUE THREAD

**Issue by mariusbancila** [XamlAnimatedGif/WpfAnimatedGif#80]
This library used to have a version number. The last one was 1.4.18. Now, version info has been removed and the assembly and file version are therefore set to 0.0.0.0. Is this intentional and if so why?

**Comment by thomaslevesque** [comment]
Hi @mariusbancila,

I'm not sure what you mean... The NuGet package has version 2.0.0, and so does the assembly.

![image](https://user-images.githubusercontent.com/1864281/89529410-fae84080-d7ec-11ea-97db-f960853080fb.png)

The version number is now determined at build time using [minver](https://github.com/adamralph/minver), which generates the version attributes automatically.

How are you using the library? Not via NuGet, I assume?

**Comment by mariusbancila** [comment]
Well, you have a build.cmd file. I used it to build the solution. The result in the WpfAnimatedGif\bin\Release\ folder is the following:

![image](https://user-images.githubusercontent.com/5336650/89536159-245e9780-d800-11ea-89e8-77234c8f4e98.png)

The Nuget package that was created has the filename: *WpfAnimatedGif.0.0.0-alpha.0.nupkg*. Inside, the DLLs have the same 0.0.0.0 version.

**Comment by thomaslevesque** [comment]
Ah, I see. In order for minver to be able to determine the version, you need to be in a git repo (i.e. not just download the sources, that won't work), and you need the tags.
In your Git clone, run `git fetch upstream --tags` to fetch the latest tags (assuming your remote name for the upstream repo is `upstream`), and it should work

**Comment by mariusbancila** [comment]
OK. That's fine. However, it would be helpful if you documented that. Because I downloaded the release you have prepared and tried to build. I did not clone. If anyone else does the same they will have the same problem. So having the building info available in the readme would be helpful.

**Comment by thomaslevesque** [comment]
Yeah, these days I tend to assume everyone is using Git...
I should probably add a "how to build" doc

**Comment by thomaslevesque** [comment]
I added a "How to build" section to the README
