### ISSUE TITLE
When changing GIFs, the animation stops working

### ISSUE THREAD

**Issue by ondrejsvorc** [XamlAnimatedGif/WpfAnimatedGif#84]
Hello,

I stumbled upon a strange problem in my program. This function is called once one of the turtle's properties change (it changes direction etc.). I upload the GIF  image into the **turtle.Body** (Body is a public Image defined in class Turtle). at the beginning of the game and animation works just fine. However, when the function attempt to change the GIF image, the animation stops working, even though I'm using the same procedure to set the GIF image. If I try to change the GIF image of an Image defined in XAML, it, for some bizarre reason, works.

I tried using the other library of yours, _XamlAnimatedGif_, 

`AnimationBehavior.SetSourceUri(turtle.Body, gifSourceTurtle);`

but it unfortunately didn't work either.

Any help is appreciated! :) 

```
private void UpdateImages()
{
    if (turtle.IsMoving && turtle.IsDirectionForward)
    {
        gifSourceTurtle = new Uri(PATH_DIRECTION_FORWARD, UriKind.Relative);
        gifSourceDirection = new Uri(PATH_DIRECTION_BACKWARDS, UriKind.Relative);
    }
    else if (turtle.IsMoving && !turtle.IsDirectionForward)
    {
        gifSourceTurtle = new Uri(PATH_DIRECTION_BACKWARDS, UriKind.Relative);
        gifSourceDirection = new Uri(PATH_DIRECTION_FORWARD, UriKind.Relative);
    }
    else if (!turtle.IsMoving && turtle.IsDirectionForward)
    {
        gifSourceTurtle = new Uri(PATH_DIRECTION_FORWARD_STOPPED, UriKind.Relative);
    }
    else if (!turtle.IsMoving && !turtle.IsDirectionForward)
    {
        gifSourceTurtle = new Uri(PATH_DIRECTION_BACKWARDS_STOPPED, UriKind.Relative);
    }

    bitmapBody = new BitmapImage();
    bitmapBody.BeginInit();
    bitmapBody.UriSource = gifSourceTurtle;
    bitmapBody.EndInit();

    ImageBehavior.SetAnimatedSource(turtle.Body, bitmapBody);

    if (gifSourceDirection != null)
    {
        bitmapBody = new BitmapImage();
        bitmapBody.BeginInit();
        bitmapBody.UriSource = gifSourceDirection;
        bitmapBody.EndInit();

        ImageBehavior.SetAnimatedSource(imgDirection, bitmapBody);
    }
}
```

**Comment by thomaslevesque** [comment]
> I tried using the other library of yours, _XamlAnimatedGif_,
> 
> `AnimationBehavior.SetSourceUri(turtle.Body, gifSourceTurtle);`
> 
> but it unfortunately didn't work either.

XamlAnimatedGif takes a URI, not a BitmapSource.

**Comment by ondrejsvorc** [comment]
> Hi @ondrejsvorc,
> 
> Sorry you're having trouble. Not sure what could be causing this... it should work fine.
> 
> Is the `ImageBehavior.AutoStart` property set to true?

Well, I tried the following: `ImageBehavior.SetAutoStart(turtle.Body, true);` and it didn't make it work.

**Comment by ondrejsvorc** [comment]
> > I tried using the other library of yours, _XamlAnimatedGif_,
> > `AnimationBehavior.SetSourceUri(turtle.Body, gifSourceTurtle);`
> > but it unfortunately didn't work either.
> 
> XamlAnimatedGif takes a URI, not a BitmapSource.

Yeah, thanks. I mistyped there. However, it doesn't make a difference. The problem still lasts.

**Comment by thomaslevesque** [comment]
> Well, I tried the following: ImageBehavior.SetAutoStart(turtle.Body, true); and it didn't make it work.

It's set to true by default, but I wonder if maybe you had disabled it

Anyway, in order to help you, I'm going to need to see more of your code. Are you able to share your project? If not, could you try to create a simple repro that you could share?

**Comment by ondrejsvorc** [comment]
> > Well, I tried the following: ImageBehavior.SetAutoStart(turtle.Body, true); and it didn't make it work.
> 
> It's set to true by default, but I wonder if maybe you had disabled it
> 
> Anyway, in order to help you, I'm going to need to see more of your code. Are you able to share your project? If not, could you try to create a simple repro that you could share?

Sure. There you have it all https://github.com/ondrejsvorc/TurtleWalk

**Comment by thomaslevesque** [comment]
Hi @ondrejsvorc,

Thanks for the repro! But I'm not sure what I'm supposed to do to reproduce the problem. It seems the only thing I can do is launch level 1, where I see the turtle cross the screen but I can't do anything. The UpdateImages method is never executed.
How should I reproduce the problem?

**Comment by ondrejsvorc** [comment]
You have to click on the images in the top right corner. One of them changes direction of the turtle and the other one stops or starts her movement. Once you do so, one their Click methods is executed - at the end of the method there is UpdateImages() being called. I hope it helps!

**Comment by thomaslevesque** [comment]
Strange... on the PC where I first tried it, the control buttons didn't show up. Neither did the language switch buttons, so the app was in Czech. I just tried on another PC, and now I see those buttons.

I was able to reproduce the issue, however I don't really understand what's going on... The problem is related to the fact that you're using relative URIs for your images. This causes the animation loading to be deferred, and it *should* be retried when the base URI is known, but for some reason, that doesn't happen.

So, I don't know the exact cause, but there's an easy fix: use absolute URIs.
i.e. instead of 
```
./Resources/Images/Turtle/turtle_direction_forward.gif
```
use
```
pack://application:,,,/Resources/Images/Turtle/turtle_direction_forward.gif
```
(and remove UriKind.Relative when you create the Uri instances)

**Comment by ondrejsvorc** [comment]
Hello,

I've been thinking a bit and I came to realise I use margins in XAML to position its content. Hence everyone sees my game wrongly on smaller monitors. I'm aware it is a bad practise and I will replace it, probably by Grid.RowDefinitions and Grid.ColumnDefinitions.

Thanks a lot for solving the problem. I really do appreciate your time! If it weren't for you, I would be probably still sitting here, racking my brain over it.

Have a nice rest of your day!

**Comment by thomaslevesque** [comment]
You're welcome. Good luck with your project!
