### ISSUE TITLE
An XDG0062 error is thrown

### ISSUE THREAD

**Issue by lifuhua123** [XamlAnimatedGif/WpfAnimatedGif#85]
When used in a user control, it will report an error when referenced to a page in xaml.But it can compile and run.
![image](https://user-images.githubusercontent.com/33051107/110584151-bc16d080-81a9-11eb-82b2-3534bcd3e164.png)
![image](https://user-images.githubusercontent.com/33051107/110584199-ce910a00-81a9-11eb-80b1-85344c098ace.png)

**Comment by thomaslevesque** [comment]
Hi @lifuhua123,

Did you resolve the problem, or did you close this issue by accident?

**Comment by lifuhua123** [comment]
The problem remains, I turned the Visual Studio XAML Designer to show only platform controls and the error alerts went away.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XamlAnimatedGif/WpfAnimatedGif"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月10日(星期三) 下午5:38
收件人:&nbsp;"XamlAnimatedGif/WpfAnimatedGif"<WpfAnimatedGif@noreply.github.com&gt;;
抄送:&nbsp;"Frank"<625851617@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [XamlAnimatedGif/WpfAnimatedGif] An XDG0062 error is thrown (#85)





 
Hi @lifuhua123,
 
Did you resolve the problem, or did you close this issue by accident?

**Comment by thomaslevesque** [comment]
I think it's an issue with the Visual Studio designer, not the library.

**Comment by AlexanderSchulz-Siemens** [comment]
@lifuhua123 I found the issue... This problem occurs, when you define an Image in your template like the following:
```xml
<Image x:Name="ProgressImage" Source="..." />
```
but in the style trigger you set the animated gif like this:
```xml
<Trigger Property="tiaPortal:ProgressBar.Type" Value="Infinite">
    <Setter Property="gif:AnimationBehavior.SourceUri" TargetName="ProgressImage" Value="..."/>
    <Setter Property="Source" TargetName="ProgressImage" Value="{x:Null}"/>
</Trigger>
```

To resolve the design time error you need to also define `gif:AnimationBehavior.SourceUri` with e.g. `x:Null`
```xml
<Image x:Name="ProgressImage" Source="..." gif:AnimationBehavior.SourceUri="{x:Null}" />
```
