### ISSUE TITLE
Some gif pics cannot display correctly.

### ISSUE THREAD

**Issue by penny681028** [XamlAnimatedGif/WpfAnimatedGif#87]
![trump_hateSpeech](https://user-images.githubusercontent.com/23231330/130400554-cde46590-f8d1-40f6-8c37-8d9744744bee.gif)
Some gif pics cannnot display correctly, it's ok when open it by any browser.

**Comment by thomaslevesque** [comment]
Hi @penny681028,

This GIF works fine in the demo app... What problem are you seeing?

**Comment by penny681028** [comment]
Some areas looks transparent like (in demo app)
![image](https://user-images.githubusercontent.com/23231330/130420271-9588f3a0-e8ec-4d6a-8dd5-78a907f989f5.png)
it should be (in edge or chrome)
![image](https://user-images.githubusercontent.com/23231330/130420606-ee2aa6a9-dd77-4a00-8c08-235095df2524.png)

**Comment by thomaslevesque** [comment]
You're using [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif/), not WpfAnimatedGif... Please open an issue in the correct project.
