### ISSUE TITLE
Does not display a specific gif file

### ISSUE THREAD

**Issue by HosseinTaarofi** [XamlAnimatedGif/WpfAnimatedGif#88]
I used the simplest mode in a simple project to display the gif file, but all the photos of this project except the submitted photo are displayed in the attachment
Sample code is used

        <Image gif:AnimationBehavior.SourceUri="Search.gif"  Width="500"  Height="300"  x:Name="imgTest" ></Image>

![Search](https://user-images.githubusercontent.com/89779141/131669025-5cdb11e7-6464-4ef9-8d1a-bedeccddae64.gif)

**Comment by thomaslevesque** [comment]
@HosseinTaarofi based on your code, it looks like you're using [XamlAnimatedGif](https://github.com/XamlAnimatedGif/XamlAnimatedGif), not WpfAnimatedGif. They have a similar name and live under the same Github organization, but they're different projects.
Please open an issue in the correct project.

**Comment by thomaslevesque** [comment]
Anyway, this GIF file is broken... It causes an end-of-stream error, because the file ends when more data is expected.
The "GIF explorer" [here](https://www.matthewflickinger.com/lab/whatsinagif/gif_explorer.asp) agrees there's something wrong with it...

**Comment by thomaslevesque** [comment]
(ok, maybe not really broken, since browsers manage to display it, but there must be something weird in the LZW compression... I haven't been able to pinpoint the problem yet)
