### ISSUE TITLE
File version lowered to 1.0.0

### ISSUE THREAD

**Issue by bdachev** [XamlAnimatedGif/WpfAnimatedGif#93]
Hi Guys, between 2.0.0 and 2.0.1 release the file version of main assembly lowered from 2.0.0 to 1.0.0.
That creates problem when installing an update using MSI package - older assebly got removed but the new one is not installed.
Any chance to fix the file version of the DLL?

**Comment by thomaslevesque** [comment]
Hi @bdachev,
Thanks for reporting this. Not sure how it happened... The package & assembly versions are controlled by [minver](https://github.com/adamralph/minver), and the only change I made between 2.0.0 and 2.0.1 has nothing to do with the assembly version. I'll look into it.

**Comment by thomaslevesque** [comment]
I think something changed in the SDK between when the 2.0.0 and 2.0.1 versions were built, which must have broken minver. And minver must have been fixed, because when I update to minver 2.5.0, it generates the correct assembly version again. I'll publish a new package ASAP.

**Comment by thomaslevesque** [comment]
I just published version 2.0.2 to NuGet (should be visible in a few minutes after the package is validated and indexed). The assembly now has the correct version.

**Comment by bdachev** [comment]
Hello Thomas, and thank you very much for your prompt responce and reaction! I tested new nuget package and it is all good now! Well done!
