### ISSUE TITLE
System.Windows.Markup.XamlParseException: Could not load 'file or assembly 'WpfAnimatedGif

### ISSUE THREAD

**Issue by songhyunbeom** [XamlAnimatedGif/WpfAnimatedGif#99]
hi
When I build in the Click-Once system, I check 32BIT BASIC for Any CPU in the main launcher project and build it.
And in a project using WpfAnimatedGif, since the build platform target is Any CPU, InitializeComponent(); In this section, an error appears as follows:
Is there a difference between WpfAnimatedGif.dll working properly or not depending on the 32-bit or 64-bit system?
System.Windows.Markup.XamlParseException: Could not load 'file or assembly 'WpfAnimatedGif, PublicKeyToken=9e7cd3b544a090dc' or one of its dependencies.The specified file could not be found.'

**Comment by CodeDiseaseDev** [comment]
same issue here 
probably just gonna give up and not use this annoying library

**Comment by thomaslevesque** [comment]
Hi @songhyunbeom,

Sorry you're having trouble. I've never seen this error with WpfAnimatedGif before, but I don't think it has anything to do with the library itself. WpfAnimatedGif targets AnyCPU, so there shouldn't be any difference between 32-bit and 64-bit. It's been used successfully on both architectures. I suspect the problem might be with ClickOnce itself. Are you sure the DLL is properly deployed?

Hi @CodeDiseaseDev,

> probably just gonna give up and not use this annoying library

Please, go ahead. You do realize that I maintain this library for free, right? It has its issues, but it has helped plenty of people. If you don't like it, don't use it, but please refrain from making disparaging comments.

**Comment by Randle-Lanre** [comment]
@thomaslevesque  First things first, this is a very useful library and thanks for the effort maintaining it, 

I also ran into the same issue today, I tried copying the file using File explorer.

upon investigating, I realized that the file need to be copied to the intended folder within solution explorer(i.e. drag into solutions explorer).
after doing this, the solution built and ran with no issues
also tried with ClickOnce and no issues.

so I believe this issue can be closed .

**Comment by thomaslevesque** [comment]
Hi @Randle-Lanre,

I don't understand why you would need to copy the file. Are you not using NuGet to install the library?

**Comment by Randle-Lanre** [comment]
> Hi @Randle-Lanre,
> 
> I don't understand why you would need to copy the file. Are you not using NuGet to install the library?

File in question is the gif file not nuget.

**Comment by thomaslevesque** [comment]
> File in question is the gif file not nuget.

OK, I think there's a confusion here. This issue was about a problem loading the assembly file (dll), not the GIF file.
